name: odda
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.4+4

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  dio: ^5.9.0
  flutter_svg: ^2.2.1
  flutter_native_splash: ^2.4.6
  top_snackbar_flutter: ^3.3.0
  slider_button: ^2.1.0
  responsive_sizer: ^3.3.1
  dropdown_button2: ^2.3.9
  syncfusion_flutter_sliders: ^31.1.19
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.2.0
  archive: ^4.0.7
  intl: ^0.20.2
  shimmer: ^3.0.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1
  carousel_slider: ^5.1.1
  flutter_launcher_icons: ^0.14.4
  connectivity_wrapper: ^1.2.8
  firebase_core: ^4.1.1
  device_info_plus: ^11.5.0
  cool_dropdown: ^2.1.1
  carousel_indicator: ^1.0.6
  otp_text_field: ^1.1.3
  otpview_sk: ^0.0.2
  super_banners: ^0.0.1
  share_plus: ^12.0.0
  currency_picker: ^2.0.21
  webview_flutter: ^4.13.0
  order_tracker: ^0.0.2
  path_provider: ^2.1.5
  # flutter_downloader: ^1.12.0  # COMMENTED OUT - Known v1 embedding issues
  file_utils: ^1.0.1
  firebase_messaging: ^16.0.2
  country_code_picker: ^3.4.0
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^19.4.2
  file_saver: ^0.3.1
  in_app_update: ^4.2.5  # COMMENTED OUT - Can cause issues
  file_picker: ^10.3.3
  url_launcher: ^6.3.2
  posthog_flutter: ^5.5.0
  package_info_plus: ^8.3.1
dependency_overrides:
  vibration: ^3.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/